server:
  port: 8088

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: kumgang
    password: 2771
    driver-class-name: oracle.jdbc.driver.OracleDriver

  #view resolver(Templete ->JSP Use)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp